apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: dogs
  name: replicaset-dogs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dogs
  template:
    metadata:
      labels:
        app: dogs
    spec:
      containers:
      - image: 356258552752.dkr.ecr.us-east-1.amazonaws.com/dogsimage-repo:v1
        name: container-dogs
        ports:
        - containerPort: 80
