apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cats
  name: cats-pod
spec:
  containers:
  - image: 356258552752.dkr.ecr.us-east-1.amazonaws.com/catsimage-repo:v1
    name: cats-container
    ports:
    - containerPort: 80
