name: Deployment to ECR
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
   
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
          AWS_REGION: us-east-1
          
      - name: Build, Test, Tag and push image ECR
        env: 
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: lab1
          IMAGE_TAG: cats
          
  
        run: |
          cd cats/
          ls -ltra
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker run -d -p 8080:80 --name lab1-cats $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker ps
          sleep 10
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
      - name: Build, Test, Tag and push to ECR
        env: 
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: lab1
          IMAGE_TAG: dogs
          
      
        run: |
          cd dogs/
          ls -ltra
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker run -d -p 8081:80 --name lab1-dogs $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker ps
          sleep 10
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  
